--creating table employee

CREATE TABLE EMPLOYEE(EMPID INT PRIMARY KEY,
						EMPNAME VARCHAR(30),
						DESIGNATION VARCHAR(20),
						DEPT VARCHAR(20),
						SALARY INT);
						
INSERT INTO EMPLOYEE VALUES(715,'JOSEPH','PRODUCT MANAGER','MARKET',45000);
INSERT INTO EMPLOYEE VALUES(728,'RAMESH','DEVELOPER','IT',50000);

--creating TRIGGER
--"C:\Users\ashra\OneDrive\Desktop\DBMSLAB\PLSQL_exp9.sql"
CREATE OR REPLACE TRIGGER total_tuples
AFTER INSERT OR DELETE OR UPDATE ON EMPLOYEE
FOR EACH ROW
DECLARE
    tuple_count INTEGER;
	PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    SELECT COUNT(*) INTO tuple_count FROM employee;
    DBMS_OUTPUT.PUT_LINE('Total number of tuples in relation is '||tuple_count);
END;
/
 INSERT INTO EMPLOYEE VALUES(816,'SILPA','DEVELOPER','IT',45000);